More informative errors
redstone-finance/redstone-smartcontracts pull request #103
Opened 2022-02-23 14:32 UTC by angrymouse

2022-02-23 17:35 UTC, ppedziwiatr requested changes

2022-02-23 17:35 UTC, ppedziwiatr commented on src/core/modules/impl/DefaultCreateContract.ts
> +      throw new Error('Unable to write Contract Source.\n'+resource.statusText.msg);
hmm. `resource`? did you mean `response`?
Also - the `statusText` is defined as a string (so there is no "msg" property):
```
post(transaction: Transaction | Buffer | string | object): Promise<{
        status: number;
        statusText: string;
        data: any;
    }>;
```

How about changing to 
```
`Unable to write Contract Source.\n${response?.statusText}`
```

2022-02-23 17:35 UTC, ppedziwiatr commented on src/core/modules/impl/DefaultCreateContract.ts
> +      throw new Error('Unable to write Contract Initial State\n'+resource.statusText.msg);
same here...

2022-03-01 16:01 UTC, angrymouse reviewed
resource means response

2022-03-01 16:01 UTC, angrymouse commented on src/core/modules/impl/DefaultCreateContract.ts
> +      throw new Error('Unable to write Contract Initial State\n'+resource.statusText.msg);
Yes, exactly

2022-03-16 11:32 UTC, merged